server:
  error:
    include-message: always
#    include-binding-errors: always

spring:
  redis:
    host: localhost
    port: 6379
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: secret
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    url: jdbc:mysql://localhost/difficultApp?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017/difficult
      repositories:
        enabled: true
  jpa:
    open-in-view: false
    show-sql: true #false
    hibernate:
      ddl-auto: create-drop #update
    properties:
      hibernate:
        format_sql: true